[package]
name = "float32"
version = "0.1.0"
authors = ["ian.graham28@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu="0.5"
futures="0.3"
winit="0.22"